// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_reach_30 = "CgkIlvKmw_sJEAIQBQ"; // <GPGSID>
        public const string achievement_reach_20 = "CgkIlvKmw_sJEAIQBA"; // <GPGSID>
        public const string achievement_reach_50 = "CgkIlvKmw_sJEAIQBw"; // <GPGSID>
        public const string achievement_reach_40 = "CgkIlvKmw_sJEAIQBg"; // <GPGSID>
        public const string achievement_gameover_10 = "CgkIlvKmw_sJEAIQCQ"; // <GPGSID>
        public const string achievement_gameover_100 = "CgkIlvKmw_sJEAIQDA"; // <GPGSID>
        public const string achievement_reach_100 = "CgkIlvKmw_sJEAIQCA"; // <GPGSID>
        public const string achievement_gameover_20 = "CgkIlvKmw_sJEAIQCg"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIlvKmw_sJEAIQAg"; // <GPGSID>
        public const string achievement_gameover_50 = "CgkIlvKmw_sJEAIQCw"; // <GPGSID>
        public const string achievement_reach_10 = "CgkIlvKmw_sJEAIQAw"; // <GPGSID>

}

